version: '3.1'

services:
  public-service:
    container_name: public-service
    build: ./public-service
    image: public-service:1.0.0
    depends_on:
      - kafka
    links:
      - kafka:kafka
    environment:
      JAVA_OPTS: "-Dspring.profiles.active=docker"
    ports:
      - 8080:8080
      
  subscription-service:
    container_name: subscription-service
    build: ./subscription-service
    image: subscription-service:1.0.0
    depends_on:
      - postgres
      - kafka
    links:
      - kafka:kafka
    environment:
      JAVA_OPTS: "-Dspring.profiles.active=docker"

  email-service:
    container_name: email-service
    build: ./email-service
    image: email-service:1.0.0
    depends_on:
      - kafka
    links:
      - kafka
    environment:
      JAVA_OPTS: "-Dspring.profiles.active=docker"
   
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  postgres:
    image: postgres:9.6
    ports:
      - 5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions