server:
  port: 8080
  
spring:
  application:
    name: subscriptions-data-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://postgres:5432/subscriptions
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://postgres:5432/subscriptions
    user: postgres
    password: postgres
  kafka:
     bootstrap-servers: kafka:9092
     consumer:
        group-id: subscriptions-1
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer