package com.andre.subscription.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.Email;

import com.andre.subscription.enums.Gender;

import io.swagger.annotations.ApiModelProperty;
import io.swagger.annotations.ApiModelProperty.AccessMode;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@Entity(name = "subscribers")
public class Subscriber implements Serializable {
	private static final long serialVersionUID = 526338188605776657L;

	@Id
	@GeneratedValue
	@ApiModelProperty(accessMode = AccessMode.READ_ONLY, value = "Auto generate. Values set will be ignored")
	private Integer id;
	
	private String firstName;
	
	@Column(nullable = false, unique = true)
	@Email
	private String email;
	
	private Date dateOfBirth;
	
	@Column(nullable = false)
	@ApiModelProperty(accessMode = AccessMode.READ_ONLY, value = "Generated by the api. Values set will be ignored")
	private Integer newsletterId;
	
	@Enumerated(EnumType.STRING)
	private Gender gender;
	
	@ApiModelProperty(accessMode = AccessMode.READ_ONLY, value = "Generated by the api. Values set will be ignored")
	private boolean subscribed = true;
}
